### ISSUE TITLE
请问一下 mac系统 返回信息中文乱码怎么解决

### ISSUE THREAD

**Issue by missWangLP** [openctp/openctp-ctp-python#10]
我进行一些操作的时候，响应信息如果是中文会变成韩文一样的乱码，请问一下这个是需要哪里配置一下呢

'StatusMsg': '놨떥틑쳡붻'
'StatusMsg': '26:틑뎷떥놨떥놻뻜뻸DCE:떱잰ힴ첬뷻횹듋쿮닙ퟷ'

**Comment by Jedore** [comment]
@missWangLP mac 系统语言，是中文吗？ 不是的话改成中文试试

**Comment by missWangLP** [comment]
语言系统是默认中文，同时推测可能转码有问题。

**Comment by missWangLP** [comment]
语言系统是默认中文，同时推测可能转码有问题。

**Comment by missWangLP** [comment]
语言系统是默认中文，之前写python的同事推测可能转码有问题。

**Comment by missWangLP** [comment]
非常感谢您，方便加一下qq么 775000538

**Comment by Jedore** [comment]
@missWangLP 此乱码问题已经解决，可以下载最新版尝试。
