### ISSUE TITLE
请问一下报单录入请求和报单撤销请求的具体参数应该如何传递，有相应的demo吗？

### ISSUE THREAD

**Issue by ycsqyq** [openctp/openctp-ctp-python#13]
<img width="515" alt="image" src="https://github.com/openctp/openctp-ctp-python/assets/9793472/9eec6392-0807-4773-9c6b-1f8ff26eaa18">

**Comment by Jedore** [comment]
> <img alt="image" width="515" src="https://private-user-images.githubusercontent.com/9793472/290699206-9eec6392-0807-4773-9c6b-1f8ff26eaa18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI2MzA1ODYsIm5iZiI6MTcwMjYzMDI4NiwicGF0aCI6Ii85NzkzNDcyLzI5MDY5OTIwNi05ZWVjNjM5Mi0wODA3LTQ3NzMtOWM2Yi0xZjhmZjI2ZWFhMTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTVUMDg1MTI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTg3MDNlNGM0MDlhMzE4OTMzM2QzY2IzOWY2ZGU4NGU4NTU1ZGIwNzhlYjhkMmIzY2FhMzMzY2EyZDcxZTk5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3OF2r-9V-r5ttHWiOP93lgJqo2TdCdM27KRs3JVTom8">

@ycsqyq 请认真读 [README.md ](https://github.com/openctp/openctp-ctp-python)

**Comment by ycsqyq** [comment]
让我认真读的是这部分吗？
<img width="884" alt="image" src="https://github.com/openctp/openctp-ctp-python/assets/9793472/2bd4cc5f-0a51-40df-a6f6-5eea728964bc">

**Comment by ycsqyq** [comment]
收到，感谢
