### ISSUE TITLE
无法订阅郑商所和期权行情

### ISSUE THREAD

**Issue by congcong009** [openctp/openctp-ctp-python#14]
使用demo程序，可以成功订阅上期所、大商所、中金所和上能所，但是无法订阅郑商所和广州期权行情，请问是什么原因？

> -------------------------------- 启动 mduser api demo 
CTP行情API版本号: v6.7.0_20230209  9:52:16.3535
行情前置:tcp://180.168.146.187:10211
初始化成功
-------------------------------- 按任意键退出 mduser api demo 行情前置连接成功
登录请求
登录成功
订阅行情请求： ('10005460', 'ap2401', 'rm2401')
订阅行情成功: 10005460
订阅行情成功: ap2401
订阅行情成功: rm2401

**Comment by congcong009** [comment]
哦，郑商所的代码有些区别，苹果的是 ap401，有行情数据了。

请问期权呢？

**Comment by Jedore** [comment]
@congcong009  关于这个你可以阅读下simnow官网的环境说明，支持哪些期货期权，如 
> https://www.simnow.com.cn/product.action 交易品种：六所所有期货品种以及上期所、能源中心、中金所所有期权品种。
确认是否支持你需要的期权， 然后用其他客户端（如快期、vnpy）验证下， 是否支持。 如果确定是 openctp-ctp 的问题，我们再进行维护。

**Comment by congcong009** [comment]
感谢J大提示，期权行情已经实现了，参考代码：MO2401-C-5400
