### ISSUE TITLE
最基本的查询下单撤单稳定吗？

### ISSUE THREAD

**Issue by hongweishang** [openctp/openctp-ctp-python#15]
生产环境在用吗？最基本的查询下单撤单稳定吗？谢谢.  这个工具转的工程一般需要改吗

**Comment by Jedore** [comment]
> 生产环境在用吗？最基本的查询下单撤单稳定吗？谢谢. 这个工具转的工程一般需要改吗

@hongweishang 这个是ctpapi官方接口以及swig转换的代码，没有修改。 生产环境可以用，但是需要谨慎，充分测试。
