### ISSUE TITLE
行情订阅异常

### ISSUE THREAD

**Issue by ycsqyq** [openctp/openctp-ctp-python#19]
当前使用版本openctp-ctp==6.7.0，系统Ubuntu 22.04.3 LTS，订阅合约数量为28个时，最后的4个合约收不到行情，或收到的行情一分钟一条，但程序没有报错。当订阅合约数量为24个时，行情就是正常的。麻烦帮忙看看是什么情况

**Comment by Jedore** [comment]
@ycsqyq 是不是合约的问题？换个合约就可以了？ 
然后可以提供下更详细的信息，比如哪个环境的行情？订阅的哪些合约？如何确定行情有问题？以便复现和排查。

**Comment by Jedore** [comment]
另外建议使用最新的版本 openctp-ctp==6.7.0.*

**Comment by ycsqyq** [comment]
并不是合约的问题，目前订阅的东航行情，使用的是tcp://116.236.239.140:42213这个节点。确定行情有问题是因为部分合约收不到行情订阅信息。。或者是一分钟一条行情。。实际跟别的看盘软件对比过。感觉目前24个合约就是极限，超过24个之后，后面的合约代码就会有问题。具体的合约代码：au2409
au2408
TL2409
IM2407
SM409
SM501
SF409
si2409
lc2407
i2409
jm2409
SA409
FG409
FG409
ag2408
ao2407
sa2407
ru2409
v2409
p2409
OI409
RM409
ru2409
al2407
al2408
IC2406
IM2406
sc2407
IH2406
sn2407
ec2408
ec2410
br2407
fu2409
ec2410
IF2406
RM409
pg2409
ni2407
CF409
lh2409
AP410
jd2409
pg2409
pb2408
UR409
sn2408
IH2407
IM2407

**Comment by Jedore** [comment]
这个行情地址也不需要验证吧，我用你发的地址和合约试试，看看24个合约之后的合约行情情况。对了，你是批量订阅所有合约还是逐个订阅所有合约？

**Comment by ycsqyq** [comment]
是按照老版本的 demo，进行的逐个订阅
![IMG_5248](https://github.com/openctp/openctp-ctp-python/assets/9793472/30729667-9761-4b75-a56d-26b9cdca5cfa)

**Comment by Jedore** [comment]
@ycsqyq 
我使用上面的行情地址和合约测试了一下，将第24及以后订阅的行情写入了文件，如图
![image](https://github.com/openctp/openctp-ctp-python/assets/17944025/3edde672-f264-40d6-bb30-d818bae9526e)
从9点01分 到 9点08分，文件大小 40kb左右的合约，基本都是1s两条行情，文件大小1KB的合约没有行情（使用快期对比了，快期也没有行情）， 看起来是正常的，暂时没能复现你说的这个场景。

**Comment by ycsqyq** [comment]
暂时还没有解决，目前保留24个合约进行测试。。另外，评测版本的6.7.2.*版本无法下载。我看版本说明上是支持的
<img width="1539" alt="image" src="https://github.com/openctp/openctp-ctp-python/assets/9793472/d9b6196e-93e9-4402-84f8-eea1b694e1f4">

**Comment by Jedore** [comment]
评测版库名你打错了

**Comment by ycsqyq** [comment]
<img width="907" alt="image" src="https://github.com/openctp/openctp-ctp-python/assets/9793472/697e28d0-0e62-4f83-ae06-63a03eee518a">
以上流程, 将 openctp-ctp 更换为 openctp-ctp-ctp 就是评测版的安装使用方式

**Comment by Jedore** [comment]
是openctp-ctp-cp，就那一处写错了，你看上面都是cp😂

**Comment by ycsqyq** [comment]
<img width="1214" alt="image" src="https://github.com/openctp/openctp-ctp-python/assets/9793472/ec22c806-1ad5-4e1d-bae2-cb4d706a0512">
还是同样的情况。。

**Comment by Jedore** [comment]
@ycsqyq 安装没有问题的，你系统和python版本的信息，都再检查检查呢，或者升级下pip， 或者提供更多的详细信息
![image](https://github.com/openctp/openctp-ctp-python/assets/17944025/63301704-b8a2-4042-b882-cbf9857dde4b)

**Comment by ycsqyq** [comment]
我这边系统是Mac，Sonoma 14.5。python版本3.9.6,pip版本升级到最新的24.1.2也还拉不下来

**Comment by ycsqyq** [comment]
我再更新下python版本试试

**Comment by ycsqyq** [comment]
目前python版本更新到3.12.0，pip版本24.1.2，仍然拉不下来
<img width="1203" alt="image" src="https://github.com/openctp/openctp-ctp-python/assets/9793472/727b6c40-2b81-41aa-8445-081d04552b7c">

**Comment by Jedore** [comment]
@ycsqyq mac下暂不支持测评版，readme里都写着呢😂

**Comment by ycsqyq** [comment]
<img width="709" alt="image" src="https://github.com/user-attachments/assets/930315e7-4fbd-4034-b5e5-44c35fcf034d">
这个歧义很强😂，感谢支持
