### ISSUE TITLE
能否增加v6.7.1_P1的评测版

### ISSUE THREAD

**Issue by ycsqyq** [openctp/openctp-ctp-python#21]
东航期货评测柜台目前仅支持v6.7.1_P1的评测版
<img width="1094" alt="image" src="https://github.com/user-attachments/assets/b8bee33a-8296-49b5-9b8b-7dfacc6b2c74">

**Comment by Jedore** [comment]
上期技术官网没有提供ctp6.7.1评测版下载，所以没有办法提供。

**Comment by ycsqyq** [comment]
联系了东航，确实是他们版本弄错了
