### ISSUE TITLE
登录请求体里的UserProductInfo最长长度是11字节吗？

### ISSUE THREAD

**Issue by shadowy** [openctp/openctp-ctp-python#24]
版本：6.7.2.7
系统：CentOS

在simnow测试时tdapi.CThostFtdcReqUserLoginField()里的UserProductInfo一直按照示例写的“demo”没有问题，
在穿透测试的时候报错：TypeError: in method 'CThostFtdcReqUserLoginField_UserProductInfo_set', argument 2 of type 'char [11]'
经修改测试，好像是限制了这个属性最多为11字节？
查看期货公司那边给的申请表里写的AppID规则是
<img width="980" alt="image" src="https://github.com/user-attachments/assets/7cb24e37-c62d-482c-b23e-5a6b0342d512">
还请J大确认下是否最长只能为11字节，谢谢。

**Comment by Jedore** [comment]
你说的是AppID，但报错的是UserProductInfo。另外最大长度你直接查看C++头文件就行，看看定义的char数组长度。手头没电脑不方便查找🔎😂

**Comment by shadowy** [comment]
不好意思，我把AppID和ProductInfo弄混了，Auth那一步之前输入了AppID，已经通过了。后面测试用期货公司的公用账户以及ProductInfo用demo登录没问题，应该是账户自身问题。

另外确认了ThostFtdcUserApiDataType.h里的这个字段是typedef char TThostFtdcProductInfoType[11];
