### ISSUE TITLE
交易demo启动提示少参数

### ISSUE THREAD

**Issue by ycsqyq** [openctp/openctp-ctp-python#25]
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/b8829d00-3d7c-4185-9169-e58ff85b9cc6">

**Comment by Jedore** [comment]
把相关信息交代清楚些， MacBookPro ?

**Comment by ycsqyq** [comment]
是的，MacBookPro。用的是td_demo的代码，CTP行情API版本号: v6.7.0_MacOS_20230412 14:00:00

**Comment by ycsqyq** [comment]
换了6.7.2.*之后，卡在这里
<img width="220" alt="image" src="https://github.com/user-attachments/assets/ad773cdc-bd4d-4f09-96d5-29cd8f81b597">

**Comment by Jedore** [comment]
参考 这个 吧 https://github.com/openctp/openctp-ctp-python/issues/20

**Comment by ycsqyq** [comment]
可以，已经登录上了，谢谢
