### ISSUE TITLE
ubuntu 22.04 下报错

### ISSUE THREAD

**Issue by ccym0769** [openctp/openctp-ctp-python#3]
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)

**Comment by Jedore** [comment]
> terminate called after throwing an instance of 'std::runtime_error' what(): locale::facet::_S_create_c_locale name not valid Aborted (core dumped)

请参考这里 https://github.com/openctp/openctp-tts-python#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by ccym0769** [comment]
解决了,系统 字符编码 GBK 缺失了, 装上就好了

**Comment by ccym0769** [comment]
@Jedore , 谢谢
