### ISSUE TITLE
容器运行时报错

### ISSUE THREAD

**Issue by congcong009** [openctp/openctp-ctp-python#4]
我用docker容器运行一个python 3.8.16-slim-buster环境，执行以下命令时

`from openctp_ctp.thostmduserapi import CThostFtdcDepthMarketDataField, CThostFtdcMdSpi`

出现报错，如下：

> terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)

我另外尝试了以下方式，也会有问题

`from openctp_ctp.thostmduserapi import CThostFtdcMdApi`

请问怎么解决呢？

**Comment by Jedore** [comment]
看readme常见问题里有答案

**Comment by congcong009** [comment]
解决，在 Dockerfile 中脚本如下：

`RUN apt update && 
    apt install -y locales && 
    echo "Y" | localedef -c -f GB18030 -i zh_CN zh_CN.GB18030`
