### ISSUE TITLE
升级为包导入后，无法订阅腾讯行情

### ISSUE THREAD

**Issue by congcong009** [openctp/openctp-ctp-python#5]
在还没有分离出python独立项目前，老的openctp python可以提供腾讯行情的接入，其中，采取文件格式进行导入，如下

`from .thostmduserapi import CThostFtdcDepthMarketDataField, CThostFtdcMdSpi, CThostFtdcMdApi`

接着只需要重写回调类就可以获得腾讯的行情订阅

`def OnRtnDepthMarketData(self, pDepthMarketData: CThostFtdcDepthMarketDataField):
··
tick = CThostFtdcMdApi.CreateFtdcMdApi()
...
tick.SubscribeMarketData()`

采用当前版本时，该类的导入方式变成

`from openctp_ctp.thostmduserapi import CThostFtdcDepthMarketDataField, CThostFtdcMdSpi`

腾讯行情订阅无效

**Comment by Jedore** [comment]
openctp-ctp是官方ctpapi的Python版，官方ctpapi不支持腾讯行情，所以openctp-ctp不支持腾讯行情。@congcong009

**Comment by congcong009** [comment]
好吧，我一直以为openctp-ctp是openctp的兼容性版本，而且 [OpenCTP](https://github.com/openctp/openctp/tree/master/ctp2QQ%E8%A1%8C%E6%83%85) 一直都支持哎，我之前都用的好好的，现在切了包调用，考虑的是统一代码，结果现在整成了需要做2套呢，很不方便。

**Comment by congcong009** [comment]
感谢J大这么快回复，我一直在使用环境判断进行调包切换，因为之前本身类库需要区分win和linux环境，我的开发是win下面，部署是在容器里，所以工作流程其实早就固化了。

我之前以为新的类库可以简化这种机制，看来是我没有理解到设计逻辑。挺期待 openctp-ctp-python 未来可以兼容这种dll的分配模式，简化使用方法 ^.^

**Comment by Jedore** [comment]
@congcong009   不太可能， 目前 openctp-ctp 的定位就是 ctpapi 的python版，不会含有其他功能 。 vn.py 也有类似的功能， 可以对接 openctp/ ctp / 等等多个柜台， 他们的方案是每个柜台的api 都有一个对应的pypi包，比如 openctp 的是 vnpy_tts , ctp的是 vnpy_ctp ， 然后通过一个gateway，来调用不同的柜台api。 你可以参考下这种gateway方案 。

**Comment by congcong009** [comment]
明白了，确实纯粹一些更好，各自有需求，应该去自定义 gateway 来实现
