### ISSUE TITLE
容器中导入失败

### ISSUE THREAD

**Issue by congcong009** [openctp/openctp-ctp-python#6]
容器中运行环境，使用的是 6.6.9_20220920\linux64 文件，出现报错如下：

> from path.linux.thostmduserapi import CThostFtdcDepthMarketDataField, CThostFtdcMdSpi
> File "/path/linux/thostmduserapi.py", line 10, in <module>
> from . import _thostmduserapi
> ImportError: libthostmduserapi_se.so: cannot open shared object file: No such file or directory

请问如何解决呢？

**Comment by Jedore** [comment]
将 so 所在路径加入环境变量 LD_LIBRARY_PATH ， 生效后重试。

**Comment by congcong009** [comment]
提前配置变量
`os.environ["LD_LIBRARY_PATH"] = "'$LD_LIBRARY_PATH':/openctp/ctp_base/dll/linux/"`

so文件也复制到这里了，然后执行导入，出现报错

> File "/openctp/ctp_base/dll/linux/thostmduserapi.py", line 10, in <module>
>     from . import _thostmduserapi
> ImportError: libthostmduserapi_se.so: cannot open shared object file: No such file or directory

**Comment by Jedore** [comment]
用Python os设置环境是有很多限制的 ，建议使用linux设置环境变量的方法设置尝试 @congcong009

**Comment by congcong009** [comment]
对，确实这样就可以了，我在启动容器的时候导入配置也行，代码如下：

```
docker run -itd ...
-e LD_LIBRARY_PATH=/root/openctp/dll/linux \
...
```

完美！推荐把这种小坑在文档里更新下 ^^

**Comment by Jedore** [comment]
pip install 没有这种问题，推荐使用。😎
