### ISSUE TITLE
tdapi:响应失败, ErrorID=3, ErrorMsg=CTP:不合法的登录

### ISSUE THREAD

**Issue by leung01** [openctp/openctp-ctp-python#9]
ping的时候  simnow的7x24td接口是返回成功的 （账号是周一注册的，今天周四）：
python3 ping.py tcp://180.168.146.187:10131
version: v6.7.0_20230209  9:52:16.3535
connected.
br-223c9ee49ecb: Success
docker0: Success
response time: 9 milliseconds

在测试demo的时候 失败了：
代码：
from tdapi import CTdSpiImpl
import config
from openctp_ctp import tdapi

spi = CTdSpiImpl(
    config.fronts["7x24"]["td"],
    config.user,
    config.password,
    config.authcode,
    config.appid,
    config.broker_id,
)

spi.is_login()

返回：
-------------------------------- 启动 trader api demo 
CTP交易API版本号: v6.7.0_20230209  9:52:16.3535
交易前置:tcp://180.168.146.187:10130
初始化成功
交易前置连接成功
> 认证
     发送请求: AppID=simnow_client_test,AuthCode=0000000000000000,BrokerID=9999,UserID=luang,UserProductInfo=
['AppID=simnow_client_test', 'AuthCode=0000000000000000', 'BrokerID=9999', 'UserID=luang', 'UserProductInfo=']
     响应成功
     响应内容: AppID=simnow_client_test,AppType=1,BrokerID=9999,UserID=luang,UserProductInfo=
> 登录
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
br-223c9ee49ecb: No such file or directory
docker0: No such file or directory
     发送请求: BrokerID=9999,ClientIPAddress=,ClientIPPort=0,InterfaceProductInfo=,LoginRemark=,MacAddress=,OneTimePassword=,Password=*******,ProtocolInfo=,TradingDay=,UserID=luang,UserProductInfo=
['BrokerID=9999', 'ClientIPAddress=', 'ClientIPPort=0', 'InterfaceProductInfo=', 'LoginRemark=', 'MacAddress=', 'OneTimePassword=', 'Password=****', 'ProtocolInfo=', 'TradingDay=', 'UserID=luang', 'UserProductInfo=']
     响应失败, ErrorID=3, ErrorMsg=CTP:不合法的登录
Traceback (most recent call last):
  File "/home/lzqw/ctp/python.py", line 15, in <module>
    spi.is_login()
TypeError: 'bool' object is not callable

**Comment by Jedore** [comment]
> /sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
/sys/firmware/dmi/tables/smbios_entry_point: Permission denied
/dev/mem: Permission denied
br-223c9ee49ecb: No such file or directory
docker0: No such file or directory

@leung01  刚试了，windows、mac都没问题，成功了。你看你日志中报的这些信息，是不是没有相关权限？

**Comment by leung01** [comment]
![企业微信截图_16995836149903](https://github.com/openctp/openctp-ctp-python/assets/134479584/fcfe279d-8505-41e0-9fbe-718f56a526c9)
换了个环境 还是不行 md可以的 方便测试一下我的账号不 luang ledata!11

**Comment by Jedore** [comment]
![image](https://github.com/openctp/openctp-ctp-python/assets/17944025/893a6483-469c-4374-a7e5-2fc0eaa1ade6)

如图，你的账号失败了，我的账号成功了，排除代码的问题了。 @leung01

**Comment by leung01** [comment]
很感谢，我问问客服

**Comment by leung01** [comment]
下单的代码有例子参考不？

**Comment by Jedore** [comment]
@leung01 demo/tdapi.py 里都有的，你仔细看看。
